/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ajonusonis' at '2/8/15 8:27 PM' with Gradle 2.2.1
 *
 * @author ajonusonis, @date 2/8/15 8:27 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
